### ISSUE TITLE
Site separation code may get confused when bonded site is nearest neighbor

### ISSUE THREAD

**Issue by jnfrye** [davidozog/Fast-Equilibration-Workflow#11]
# Bug description
Currently, in function [``separate_overlapping_sites(...)`` of nearest_neighbors.py](https://github.com/davidozog/Fast-Equilibration-Workflow/blob/ghost_cells/src/backmapping/backmap_cones_package/nearest_neighbors.py), the following situation can occur

* A site can have its nearest neighbor be a site it is bonded to
* This causes the code to stop searching for nearest neighbors to this site and move on to the next site
    * This is to avoid a site being repelled from its bonded sites, which would stretch out all the chains
* However, this could cause two inaccuracies:
    * It is possible for a site to be repelled such that it is very close to a nearest neighbor, which is undesirable (probably a rare situation, but still possible)
    * It is also possible that a site could have both its nearest neighbor and a site from another chain closer than the threshold. If the nearest neighbor is closer, the site will be skipped over and remain close to both

# Solution
I think the easiest solution is to have a separate threshold radius for bonded sites. 

This is an easy change, and allows us to fine-tune the separation when neighbors are bonded versus not bonded.

**Comment by jnfrye** [comment]
In 9962381 I coded the backend for having two separation thresholds. I still need to figure out how to calculate the LJ-potential for PE.

**Comment by jnfrye** [comment]
As per @mguenza, the LJ-potential minimum is given in TABLE 1 of [10.1063/1.4875923](http://dx.doi.org/10.1063/1.4875923)

@davidozog, does the code currently calculate this value or use this value? Or do we need to add this

**Comment by davidozog** [comment]
The LJ parameters for all UA simulations generated with in the in.parent.UA.template file are currently hard-coded to the values in Table 1 of that paper.  That happens [right here](https://github.com/davidozog/Fast-Equilibration-Workflow/blob/master/templates/in.parent.UA.template#L25).  Relevant Lammps doc is [here](http://lammps.sandia.gov/doc/bond_harmonic.html).  Other than that, I don't know of any LJ coefficients running around the workflow.  The CG component has its own bond_style.

**Comment by jnfrye** [comment]
I am working on sending the LJ parameters to backmap_cones; see branch [putting_lj_params_in_backmap_cones](https://github.com/davidozog/Fast-Equilibration-Workflow/tree/putting_lj_params_in_backmap_cones) for progress

**Comment by jnfrye** [comment]
Implemented; see 3f78d8f
