### ISSUE TITLE
Error running automated_fastequil

### ISSUE THREAD

**Issue by pgromano** [davidozog/Fast-Equilibration-Workflow#14]
Hey All, 

I installed the workflow, and set up my path. I have the lammps-daily build installed with MPI (and I should have POEMS as well). When I try to run with and without mpirun...

`automated_fastequil -nchain 100 -nmonomer 200 -sitesperchain 4 -cg_timesteps 10  -cg_steps_per_frame 2 `

I get the following error

`Traceback (most recent call last):
  File "/usr/local/bin/automated_fastequil", line 214, in <module>
    main()
  File "/usr/local/bin/automated_fastequil", line 131, in main
    workflow.run_lammps('in.%s' % sim)
  File "/usr/local/bin/workflow.py", line 220, in run_lammps
    ' < generated_lammps_input_files/' + input_filename,
  File "/home/promano/Programs/anaconda3/envs/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'MPIEXEC'`

I can run lammps with MPI and I have mpich installed as well. Any ideas where I'm going wrong?

**Comment by davidozog** [comment]
Excellent, I'm glad to see you're trying out the tools.

This is possibly because MPIEXEC is not set.  It's described briefly in the Installation section of the readme.  You can start with something like:

`export MPIEXEC="mpirun -np 4"`

Then see if it works.

Let me also say that instead of "automated_fastequil" you might be more interested in the "Helper Tools", which are partially described on the Wiki.  We're going to add more tools for things like RMSD, plotting pressure from Lammps output etc.  These exist, but aren't documented yet, so just let me know if you're interested in them.

**Comment by pgromano** [comment]
Great! It's still not working (but new error!) It looks like the problem might be that I didn't compile lammps from source and installed set up from the Ubuntu repositories. 

`KeyError: 'LAMMPS_BIN`

I looked around at some of the Helper Tools and individually the chain creator and backmap_cones work. I'd love to play around with these on a more individual level.

**Comment by davidozog** [comment]
It appears that you missed steps 1, 2, and 3 in the installation section of the Readme file.  Sorry, I should have said that before.  Do you see those?  It could probably be a little more clear... the installation isn't done until those steps are complete.  We could make it more automagical, but at the same time I like the ability to change how MPI and Lammps are run without having to rebuild.

So yes, you also have to set LAMMPS_BIN to whichever binary you are using when you run the workflow.  For the Ubuntu repository, it would probably be something like "lammps" or maybe "lmp_mpi".  However you run Lammps, try setting LAMMPS_BIN to that binary.

Unfortunately, you might have trouble running the workflow with the Ubuntu repository.  Lammps development isn't the best for backwards compatibility.  I've tested version 9Dec14 and 10Aug15.  Josh may have tested others.  But we always build from source.

You can also just run it on Frida if you put this in your ~/.bashrc
```
export PATH=/home/ozog/Repos/Fast-Equilibration-Workflow/bin:$PATH
export MPIEXEC="mpirun -np 8"
export LAMMPS_BIN=lmp_mpi
```

**Comment by pgromano** [comment]
Hmm, it's still not working, so I'm going to recompile lammps from source and see if that fixes things. In the mean time I'll play around with it on Frida. Thanks for the help!

**Comment by davidozog** [comment]
What's your error?  On Ubuntu 14.04 I get this:
`ERROR: Unknown command: comm_modify mode single   cutoff 50.0   vel yes (../input.cpp:218)`

Are you on 14.04?  There's probably an elegant way to fix this, but I should file the bug, especially if we see the same thing.

**Comment by pgromano** [comment]
My error is basically complaining about `LAMMPS_BIN`. I think that the build of Lammps I had may not actually be set up for MPI.

`Traceback (most recent call last):
  File "/usr/local/bin/automated_fastequil", line 214, in <module>
    main()
  File "/usr/local/bin/automated_fastequil", line 131, in main
    workflow.run_lammps('in.%s' % sim)
  File "/usr/local/bin/workflow.py", line 220, in run_lammps
    ' < generated_lammps_input_files/' + input_filename,
  File "/home/promano/Programs/anaconda3/envs/py27/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'LAMMPS_BIN'`

**Comment by davidozog** [comment]
Hmmm.  Looks like LAMMPS_BIN is still not set correctly.  What does this say?
`echo $LAMMPS_BIN`
`which lammps`

**Comment by pgromano** [comment]
I had accidently set `export LAMMPS_bin` so that was messing me up. I also uninstalled the lammps-daily build and installed the default repository version for Ubuntu 14.04 and I'm getting the same error as you.

**Comment by davidozog** [comment]
Cool.  I'll see what I can do about that error.
